### PR TITLE
Adding support for Langswitcher

### PR DESCRIPTION
**Pull request by dartcafe**

### CODE REVIEW

**Comment by dartcafe** [comment]
@tranduyhung: Any chance to get this merged and released?

**Comment by tranduyhung** [comment]
@dartcafe 

I am looking for a way to make the footer multilingual. The only solution I have now is using pages instead of putting the content in the theme's configuration, but doing this will break the site when we update the theme. If you have any solutions for this please feel free to make pull requests or let me know.

**Comment by dartcafe** [comment]
I rhought it woud be easier to support the langswitcher plugin, as we do on our page. It works as expected. 
See https://www.weltcup-dormagen.de

**Comment by tranduyhung** [comment]
The content of your footer is always in German, even in English version, this is what some users don't want and this is what I am trying to find a solution for.

**Comment by dartcafe** [comment]
Removal from personal PR list

**Pull request closed without merging**
